### ISSUE TITLE
Please how would you add Server-Sent Events to your library for simple self hosted streaming

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [JamesDunne/aardwolf#3]
Please how would you add Server-Sent Events to your library for simple self hosted streaming

thanks.

**Comment by JamesDunne** [comment]
Seems like it shouldn't be too hard, according to http://www.w3schools.com/html/html5_serversentevents.asp

Looks like it's just HTTP headers to be sent. I've never done it myself so I can't tell you exactly how.

**Comment by CharlesOkwuagwu** [comment]
Thanks
